### PR TITLE
Refactor code to eliminate inefficient FOR-loops and use .join() isntead

### PR DESCRIPTION
**Pull request by maldil**
Thank you very much for your excellent work in SPFlow.
I am a graduate student at the University of Colorado-Boulder, studying the best practices of evolving ML codes. According to our research, one of the best practices is migration of loop-based computations since it typically results in better speed and code quality. Therefore, we made the following changes in SPFlow, which remove the FOR loop and use join(). I carefully checked the modification to ensure that it does not break the code. I will gladly contribute. Please help me to merge this.

### CODE REVIEW

**Comment by maldil** [comment]
Hi @steven-lang 
Thanks for responding to the pull request. I'm curious if you were able to integrate the pull request or if it was closed because it doesn't adhere to the correct pull request standards. As a newcomer, if there are any standards that must be followed, I would be pleased to comply if you could help me. I'm grateful in advance.

**Comment by albertz** [comment]
@maldil Note that the code change is not equivalent. Before the change, the string started exactly with one space (`" "`) but not more, and ended with `" * "`. After your change, the string started with two spaces `"  "` and did not end with `" * "`.

Btw, I saw that you did quite a lot of similar PRs in various projects. Are those done in an automatic way? You should say so if that is the case.

**Comment by maldil** [comment]
@steven-lang 
Thanks for responding. 
I performed a small experiment. 
```
  xx = ["a","e","i","o","u"]
  print(" * ".join(xx))
```
The output of the above code is `a * e * i * o * u`, so it does not start with the `" * "`, hence the added space will be the starting character (`" "`) . However, I agree that the end character will not be the `" * "` in the submitted PR. If you agree and want me to make the change, I'll be pleased to do it.

I appreciate you checking the PRs that were sent for our ongoing work. I'd like to inform you that generating PR is semi-automatic. I carefully review each PR to make sure it adheres to the guidelines, due to the fact that every project has its own set of pull request policies. Once more, many thanks.

**Comment by steven-lang** [comment]
The PR was closed because your "contribution" is essentially spam. You've created the same PR to a bunch of other repos without any clue of what your doing. Do you really think a debug print statement that concatenates a bunch of strings needs performance optimizations? You've done the same in the PyTorch repo and suggested some non-sense "optimization" with numpy in a jit function while the relevant code doesn't even support numpy.

Please stop wasting peoples time by automatically creating pull requests for non-issues just to get into the contributors list of open-source projects.

**Pull request closed without merging**
