### PR TITLE
Run pyupgrade

### PR DESCRIPTION
**Pull request by felixdivo**
I ran the [pyupgrade](https://github.com/asottile/pyupgrade) tool to update some old code. It would be tedious to do this manually. 

Do you agree with the changes?

To reproduce:
```shell
pip install pyupgrade
python -m pyupgrade --py36-plus $(find . -name "*.py")
```

What is the lowest python version supported by the library? I couldn't find that info. I guess 3.8 could be sensible based on [the end-of-life dates](https://endoflife.date/python). I ran it for 3.6, but can quickly extend it to also include changes geared to higher versions.

### CODE REVIEW

**Comment by braun-steven** [comment]
I just dropped 3.6 as this version also had some issues with torch>=1.10.2 anyway (or rather the other way around).

I'm not sure why this PR didn't trigger the Actions workflow to run the tests. Do you know if it's possible to trigger that manually?

**Comment by felixdivo** [comment]
Then I'll run the tool to upgrade the code to 3.7+ (one version higher than previously).

**Comment by felixdivo** [comment]
> Then I'll run the tool to upgrade the code to 3.7+ (one version higher than previously).

This did not change anything. The next version that _would_ have changed something was 3.9+, but that would needlessly drop support for 3.7 and 3.8.

I think this can now be merged.

**Comment by braun-steven** [comment]
Great, thanks again!

**Pull request merged**
