### PR TITLE
Fix classmethod naming convention (self -> cls)

### PR DESCRIPTION
**Pull request by felixdivo**
I was a bit confused by some coding conventions:

```python
    @classmethod
    def accepts(self, signatures: List[FeatureContext]) -> bool:
```

Normally, I'd expect a `classmethod` to accept `cls` (short for class, not an actual instance yet) instead of `self` (which is more like this in other languages, i.e. a concrete instance).

This is quite common, i.e. run `git ls-files | xargs grep -Pzo "(?s)@classmethod\\s+ def (\w|_)+\\(self" --color`. Yes, I am aware that this is just convention. But I think it is a very useful one in Python. :stuck_out_tongue_closed_eyes: 

Specifically, the PR replaces `@classmethod\s*\n\s+def (\w|_)+\()self` with `$1cls`.

### CODE REVIEW

**Comment by felixdivo** [comment]
Attention: This also contains a sneaky change to run the CI checks in more places.

**Comment by braun-steven** [comment]
Thanks! I agree, that we should go with `cls` instead of `self` to keep it consistent with python conventions.

There seem to be two issues though:

Your commit only replaces the variable names in the method header and not in the body, see e.g.:
https://github.com/SPFlow/SPFlow/blob/7fc1f1585fef959527afe857bb930a85143478e1/src/spflow/torch/structure/general/nodes/leaves/parametric/geometric.py#L117-L128

Multiline method definitions are unaffected:

https://github.com/SPFlow/SPFlow/blob/7fc1f1585fef959527afe857bb930a85143478e1/src/spflow/base/structure/general/layers/leaves/parametric/cond_poisson.py#L124-L127

Also, I'm unsure about this one but did your CI change break the test? I'm confused as to why the tests fail after your commit:

https://github.com/SPFlow/SPFlow/actions/runs/3549810284/jobs/5962588417

**Comment by braun-steven** [comment]
Ok, nevermind regarding the breaking GitHub Actions, it's related to https://github.com/actions/setup-python/issues/544#issuecomment-1320295576

**Comment by felixdivo** [comment]
Oh thank you! I was about to tackle this.

**Pull request merged**
